// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	pb "github.com/aloknerurkar/msuite-services/common/pb"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PaymentsClient is the client API for Payments service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentsClient interface {
	NewCharge(ctx context.Context, in *ChargeReq, opts ...grpc.CallOption) (*Charge, error)
	RefundCharge(ctx context.Context, in *RefundReq, opts ...grpc.CallOption) (*Refund, error)
	Get(ctx context.Context, in *pb.UUIDs, opts ...grpc.CallOption) (*Charges, error)
	List(ctx context.Context, in *pb.ListReq, opts ...grpc.CallOption) (*Charges, error)
}

type paymentsClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentsClient(cc grpc.ClientConnInterface) PaymentsClient {
	return &paymentsClient{cc}
}

func (c *paymentsClient) NewCharge(ctx context.Context, in *ChargeReq, opts ...grpc.CallOption) (*Charge, error) {
	out := new(Charge)
	err := c.cc.Invoke(ctx, "/payments.Payments/NewCharge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsClient) RefundCharge(ctx context.Context, in *RefundReq, opts ...grpc.CallOption) (*Refund, error) {
	out := new(Refund)
	err := c.cc.Invoke(ctx, "/payments.Payments/RefundCharge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsClient) Get(ctx context.Context, in *pb.UUIDs, opts ...grpc.CallOption) (*Charges, error) {
	out := new(Charges)
	err := c.cc.Invoke(ctx, "/payments.Payments/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsClient) List(ctx context.Context, in *pb.ListReq, opts ...grpc.CallOption) (*Charges, error) {
	out := new(Charges)
	err := c.cc.Invoke(ctx, "/payments.Payments/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentsServer is the server API for Payments service.
// All implementations must embed UnimplementedPaymentsServer
// for forward compatibility
type PaymentsServer interface {
	NewCharge(context.Context, *ChargeReq) (*Charge, error)
	RefundCharge(context.Context, *RefundReq) (*Refund, error)
	Get(context.Context, *pb.UUIDs) (*Charges, error)
	List(context.Context, *pb.ListReq) (*Charges, error)
	mustEmbedUnimplementedPaymentsServer()
}

// UnimplementedPaymentsServer must be embedded to have forward compatible implementations.
type UnimplementedPaymentsServer struct {
}

func (UnimplementedPaymentsServer) NewCharge(context.Context, *ChargeReq) (*Charge, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewCharge not implemented")
}
func (UnimplementedPaymentsServer) RefundCharge(context.Context, *RefundReq) (*Refund, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefundCharge not implemented")
}
func (UnimplementedPaymentsServer) Get(context.Context, *pb.UUIDs) (*Charges, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedPaymentsServer) List(context.Context, *pb.ListReq) (*Charges, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedPaymentsServer) mustEmbedUnimplementedPaymentsServer() {}

// UnsafePaymentsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentsServer will
// result in compilation errors.
type UnsafePaymentsServer interface {
	mustEmbedUnimplementedPaymentsServer()
}

func RegisterPaymentsServer(s grpc.ServiceRegistrar, srv PaymentsServer) {
	s.RegisterService(&Payments_ServiceDesc, srv)
}

func _Payments_NewCharge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChargeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServer).NewCharge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payments.Payments/NewCharge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServer).NewCharge(ctx, req.(*ChargeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payments_RefundCharge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefundReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServer).RefundCharge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payments.Payments/RefundCharge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServer).RefundCharge(ctx, req.(*RefundReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payments_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.UUIDs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payments.Payments/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServer).Get(ctx, req.(*pb.UUIDs))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payments_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.ListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payments.Payments/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServer).List(ctx, req.(*pb.ListReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Payments_ServiceDesc is the grpc.ServiceDesc for Payments service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Payments_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payments.Payments",
	HandlerType: (*PaymentsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewCharge",
			Handler:    _Payments_NewCharge_Handler,
		},
		{
			MethodName: "RefundCharge",
			Handler:    _Payments_RefundCharge_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Payments_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Payments_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payments.proto",
}
